<?php
/**
 * Init function for adding the external file
 */

function general_init()
{
	//to add the css file
	drupal_add_css(drupal_get_path('module', 'general').'/general.css');
	
}


/**
 * Form alter function
 * by using this form_alter function we can alter the form without editing core module
 */
function general_form_alter(&$form, $form_state, $form_id)
{

	//registration page
	if($form['#form_id']=='user_register_form')
	{
		$base_path=base_path().'sites/default/help_icon.gif';
		$form['photo_paypal_icon']=array('#markup'=>"<p><span title='Your Paypal account ID' id='paypal_icon' style='float:right;padding-right:102px;padding-top:18px;color:red;'><img src='$base_path'></img></span></p>",'#weight'=>'5');
		//add the form submit function for insert the user role in the user table
       		 $form['#submit']['1']= 'user_role_insertion'; 
	}

	//profile edit page
	
	if($form['#form_id']=='user_profile_form')
	{

		global $user;
		$uid=$user->uid;
		$base_path=base_path().'sites/default/help_icon.gif';
		$form['photo_paypal_icon']=array('#markup'=>"<p><span title='Your Paypal account ID' id='paypal_icon' style='float:right;padding-right:102px;padding-top:18px;color:red;'><img src='$base_path'></img></span></p>",'#weight'=>'5');

	}
}

/**
 *Function for insert the user role in the users table when submit the create account submit button
 */
function user_role_insertion($form,&$from_state)
{
	

	//call class function
	$photographer=new photographer_model();
	$user_role=$photographer->get_role_id();
	$role_id=$user_role->rid;

	$uid=$form['#user']->uid;

	//call the class function for update the user role in the user table
	$photographer->user_role_update($role_id,$uid);
	
	//call the class function for insert the user role in the user roles table
	$photographer->user_role_id_insert($role_id,$uid);

	
	
}


