<?php

/**
 * @file
 * Common tools for Runmemo.com
 * 
 * This module provides common functions that can be reused in other
 * custom modules.
 */

require_once(DRUPAL_ROOT . '/' . drupal_get_path('module', 'ocr') . '/ocr_product_node_saver.inc');

/**
 * Returns rendered price slider
 * @return rendered array
 */
function get_rendered_slider() {
  $slider =  
    '<div id="price-container" class="price-slider">
      <div>
      	<label for="amount" class="field-label" style="float: left">My price:</label>
      	<span id="amount" style="margin-left: 10px"></span>    
      </div>
      <div id="price"></div> 
    </div>';
  return $slider;
}

/**
 * Returns rendered runners number box
 * @return rendered array
 */
function get_rendered_runner_number_box($nid) {
  
  $productSaver = new ProductNodeSaver($nid);
  $numbers_str = $productSaver->GetNumbersStr(); 
        
  $numbers_box =
    '<label for="product-node-runner-number" class="field-label">Runner numbers:</label>
    <input name="product-node-runner-number" id="product-node-runner-number" value="'
    . $numbers_str     
    . '"/>';
  
  return $numbers_box;
  
}