<?php

/**
 * @file
 * Common tools for Runmemo.com
 * 
 * This module provides common functions that can be reused in other
 * custom modules.
 */

/**
 *
 * @return rendered array
 */
function get_rendered_slider() {
  $slider =  
  '<div id="price-container" class="price-slider">
      <div>
      	<label for="amount" class="field-label" style="float: left">My price:</label>
      	<span id="amount" style="margin-left: 10px"></span>    
      </div>
      <div id="price"></div> 
    </div>';
  return $slider;
}