 <?php
/**
 * Init function for adding the external file
 */

function photographer_init()
{
	//to add the js file
	drupal_add_js(drupal_get_path("module","photographer")."/js/photographer.js");
	drupal_add_css(drupal_get_path('module', 'photographer') . '/photographer.css');
}

/** 
 * Create the hook menu for each page 
 * by using this we can map to the related page
 * @return 
 * return the custom created menus
 */
function photographer_menu()
{
	
	//url for photographer
	$items['photographer'] = array(
			    'title' => 'Upload Photos',
			    'description' => t('View the objects in a bucket on your Amazon S3 account.'),
			    'page callback' => 'photographer_upload_photos',
			    'page arguments' => array(1),
			    'access arguments' => array('access_photographer'),
			    'type' => MENU_CALLBACK,
			  );
	return $items;

}

/**
 * Set the pemission for each url in the admin side
 * so we can the restrict the particular page to accessed by the anonymouse user
 * @return 
 * Return the access permission
*/
function photographer_permission()
{

	return array(
			    

			    'access_photographer' => array(
			      'title' => t('Access photographer'),
			      'description' => t('Access photographer'),
			      'restrict access' => TRUE,
			    ),
		     );
}

/** 
 * Photographer page
 * where the photographer can upload the photos by selecting the event
 * uploaded photos are stored in the amazon_s3
*/
function select_event_function()
{
	$form = array();
	$form['events_select']=array('#type'=>'select','#title'=>'Select Event','#id'=>'event_select','#attributes'=>array('onchange'=>'return select_event_upload();'));
	$form['events_select']['#options']=array('select_event'=>"Select Event");
	//select event options from content type 'event'
	$photographer_upload = new photographer_upload();
	
	//get the event name from taxonomy catalog terms
	$event_name=$photographer_upload->get_event_name();
	foreach($event_name as $event_name_value)
	{
		$event_title = $event_name_value->name;
		$event_title_nid = $event_name_value->tid;
		$form['events_select']['#options'][$event_title_nid]=$event_title;
	}
	return $form;

}
/**
 * Drag and drop upload form creation
 */
function photographer_drag_and_drop_form($form,&$form_state) {
  $form = array();
  $form['#attributes'] = array('enctype' => 'multipart/form-data');

  $form['box'] = array(
    '#type' => 'fieldset',
    '#title' => t(''),
    '#collapsible' => FALSE,
    '#collapsed' => FALSE,
  );

  $form['box']['file'] = array(
    '#type' => 'plupload',
    '#title' => t('File to upload'),
    '#description' => t('Pick a file to upload'),
    '#size' => 40,
  );

  $form['box']['upload'] = array('#type' => 'submit', '#value' => 'Upload','#attributes'=>array('onclick'=>'return drag_drop_upload_validation();'));
  $form['box']['selected_event']=array('#type'=>'textfield','#title'=>'','#id'=>'selected_event_drag');
  return $form;
}

/** 
 * Drag and drop submit function
 * @param $form
 * $form gives the form values from the photographer upload form values
 */

function photographer_drag_and_drop_form_submit($form, &$form_state) {

  global $user;

  
  
  $uid=$user->uid;

  $s3 = amazon_s3_get_instance();

  //for loop for count the uploaded files resource 2
  for($i=0;$i<count($form['box']['file']['#value']);$i++)
  {
      
          
        // We create a new node object  
        $node = new stdClass(); 
        // content type
        $node->type = "product";         
        //node title
        $node->title = $form['box']['file']['#value'][$i]['name'];
        //set language
        $node->language = 'und'; 
        //user id
        $node->uid = $uid; 
        node_object_prepare($node); 
        
        // Let's add standard body field
        $node->body[$node->language][0]['value'] = 'This is a body text';
        $node->body[$node->language][0]['summary'] = 'Here goes a summary';
        $node->body[$node->language][0]['format'] = 'filtered_html'; 

        // Create a File object
       
       $file_path = $form['box']['file']['#value'][$i]['tmppath']; 
      
               
        $file = (object) array(
                'uid' => $uid,
                'uri' => $file_path,
                'filemime' => file_get_mimetype($file_path),
                'status' => 1,
                                
        ); 
        
       
        // Save the file to the root of the files directory. You can specify a subdirectory, for example, 'public://images'
        $file = file_copy($file, 's3://');  
        $node->uc_product_image['und'][0] = (array)$file; //associate the file object with the image field:
   
        //add taxonamy terms
        $taxonomy_term_id = $form['box']['selected_event']['#value'];  
        $node->taxonomy_catalog[$node->language][]['tid'] = $taxonomy_term_id;
        
        $node = node_submit($node); // Prepare node for a submit
        node_save($node); // After this call we'll get a nid 
  
         
          
  
  }
  $form_state['redirect'] = "photographer";
}



/**
 * Call back function for photographer
 * @return 
 * return form in the page
 */
function photographer_upload_photos() {
  $select_event=drupal_render(drupal_get_form('select_event_function'));
  $file_upload_form = drupal_render(drupal_get_form('photographer_drag_and_drop_form'));
  $style="<div style='display:none' id='upload_section' >$file_upload_form</div>";
  return $select_event.$style;
}
