 <?php 
/**
 * Init function for adding the external file
 */

function photographer_init(){
    //to add the js file
    drupal_add_js(drupal_get_path("module","photographer")."/js/photographer.js");
    drupal_add_css(drupal_get_path('module', 'photographer') . '/photographer.css');
    drupal_add_css(drupal_get_path('theme', 'runmemo') . '/css/style.css');
}

/** 
 * Create the hook menu for each page 
 * by using this we can map to the related page
 * @return 
 * return the custom created menus
 */
function photographer_menu(){
	
    //url for photographer
    $items['photographer'] = array(
                        'title' => 'Upload Photos',
                        'description' => t('View the objects in a bucket on your Amazon S3 account.'),
                        'page callback' => 'photographer_upload_photos',
                        'access arguments' => array('access_photographer'),
                        'type' => MENU_CALLBACK,
                        );
  
    return $items;

}

/**
 * Set the pemission for each url in the admin side
 * so we can the restrict the particular page to accessed by the anonymouse user
 * @return 
 * Return the access permission
*/
function photographer_permission(){

    return array(
                        'access_photographer' => array(
                        'title' => t('Access photographer'),
                        'description' => t('Access photographer'),
                        'restrict access' => TRUE,
                        ),
                 );
}

/** 
 * Photographer page
 * where the photographer can upload the photos by selecting the event
 * uploaded photos are stored in the amazon_s3
*/
function select_event_function(){
    
    $form = array();

    $form['event_title']=array('#markup'=>'<div class="select_event_title" >Select Event</div>');

    $form['events_select']=array('#type'=>'select','#title'=>'','#id'=>'event_select','#attributes'=>array('onchange'=>'return select_event_upload();'), '#prefix'=>'<div id="event_drop">', '#suffix'=>'</div>');

    $form['events_select']['#options']=array('select_event'=>"Select Event");


    //select event options from content type 'event'
    $event_helper_object = new event_helper();

    //get the event name from content type 'event'
    $event_name=$event_helper_object->get_events();
    foreach($event_name as $event_name_value)
    {
            $event_title = $event_name_value->title;
            $event_title_nid = $event_name_value->nid;
            $form['events_select']['#options'][$event_title_nid]=$event_title;
    }

    if((is_numeric(arg(1))) && (arg(1) != ''))
    {
        $default=arg(1);
        $form['events_select']['#default_value']=$default;
    }

    return $form;
}
/**
 * Drag and drop upload form creation
 */
function photographer_drag_and_drop_form($form,&$form_state) {
  $form = array();
  $form['#attributes'] = array('enctype' => 'multipart/form-data');

  $form['box'] = array(
    '#type' => 'fieldset',
    '#title' => t(''),
    '#collapsible' => FALSE,
    '#collapsed' => FALSE,
  );

  $form['box']['file'] = array(
    '#type' => 'plupload',
    '#title' => t(''),
    '#description' => t(''),
    '#size' => 40,
     '#prefix'=>'<div class="upload_title">Upload Photos</div><span class="guide-line">Please read our '.l("style guide","style-guide",array(
                    'attributes' => array(
                      'id' => 'guide',
                      
                     )
          )).' before uploading the photos</span>'
  );

  $form['box']['upload'] = array('#type' => 'submit', '#value' => '','#attributes'=>array('onclick'=>'return drag_drop_upload_validation();'));
  $form['box']['selected_event']=array('#type'=>'textfield','#title'=>'','#id'=>'selected_event_drag');
  return $form;
}

/** 
 * Drag and drop submit function
 * @param $form
 * $form gives the form values from the photographer upload form values
 */

function photographer_drag_and_drop_form_submit($form, &$form_state) {
  
  
  $selected_event = $form['box']['selected_event']['#value'];
  $price = node_load($selected_event)->field_pricing['und']['0']['value'];
  
  global $user;
  $uid=$user->uid;
  //for loop for count the uploaded files resource 2
  for($i=0;$i<count($form['box']['file']['#value']);$i++){
          
        // We create a new node object  
        $node = new stdClass(); 
        // content type
        $node->type = "product";         
        //node title
        $node->title = $form['box']['file']['#value'][$i]['name'];
        //set language
        $node->language = 'und'; 
        //user id
        $node->uid = $uid; 
        node_object_prepare($node); 
        
        // Let's add standard body field
        $node->body[$node->language][0]['value'] = 'This is a body text';
        $node->body[$node->language][0]['summary'] = 'Here goes a summary';
        $node->body[$node->language][0]['format'] = 'filtered_html'; 

      
       
      
		
		//////////Change file extension////////////////////////
        
        $file_path = drupal_realpath('temporary://');
  	
	$temp_name = basename($form['box']['file']['#value'][$i]['tmppath']);
       
        $temp_path = $file_path .'/'. $temp_name;
               
        chmod($temp_path,'777');
       
        $original_name = $file_path  .'/'.$form['box']['file']['#value'][$i]['name'];
       
        rename($temp_path,$original_name);
       
        $file = (object) array(
                'uid' => $uid,
                'uri' => 'temporary://'.$form['box']['file']['#value'][$i]['name'],
                'filemime' => file_get_mimetype($form['box']['file']['#value'][$i]['tmppath']),
                'status' => 1,
                               
        );
	   
        //file moves from temp to public folder
        $file = file_move($file, 'public://'); 

        //Creating thumbnail image
        $thumb_url=image_style_url('thumbnail', 'public://'.$form['box']['file']['#value'][$i]['name']); 
        @file_get_contents($thumb_url);

        //Creating preview image
        $preview_url=image_style_url('preview-with-watermark', 'public://'.$form['box']['file']['#value'][$i]['name']); 
        @file_get_contents($preview_url);
		
		
        $node->uc_product_image['und'][0] = (array)$file; //associate the file object with the image field:
   
         if(($selected_event == '')){
            $node->field_event_reference['und']['0']['nid'] = arg(1);
        }
        else{
            $node->field_event_reference['und']['0']['nid'] = $form['box']['selected_event']['#value'];
        }
        if($price != ''){
          $node->sell_price = $price; 
        }                 
        $node = node_submit($node); // Prepare node for a submit
               
        node_save($node); // After this call we'll get a nid       
        
        //file_unmanaged_delete('temporary://'.$form['box']['file']['#value'][$i]['name']);
  }

  drupal_set_message("Files uploaded successfully");
  $form_state['redirect'] = "photographer";
}


/**
 * Call back function for photographer
 * @return 
 * return form in the page
 */
function photographer_upload_photos() {
  $select_event=drupal_render(drupal_get_form('select_event_function'));
  $file_upload_form = drupal_render(drupal_get_form('photographer_drag_and_drop_form'));
  $style="<div style='display:none' id='upload_section' >$file_upload_form</div>";
  return $select_event.$style;
}
