<?php
/**
 * Init function for adding the external file
 */

function runner_init()
{
	//to add the js file
	drupal_add_js(drupal_get_path("module","runner")."/runner.js");
	drupal_add_css(drupal_get_path('module', 'runner') . '/runner.css');
}

///////////////////////////////////////////////////////////
/** 
 * Create the hook menu for each page 
 * by using this we can map to the related page
 * @return
 * return menu items
 */
function runner_menu()
{
	//url for runner
	$items['runner'] = array(
			    'title' => 'Photo Gallery',
			    'description' => t('View the objects in a event on your Amazon S3 account.'),
			    'page callback' => 'amozon_s3_show_images',
			    'page arguments' => array(1),
			    'access arguments' => array('access_runner'),
			    'type' => MENU_CALLBACK,
			  );

	return $items;

}

/**
 * Set the pemission for each url in the admin side
 * so we can the restrict the particular page to accessed by the anonymouse user
*/
function runner_permission()
{

	return array(
			    'access_runner' => array(
			      'title' => t('Access runner'),
			      'description' => t('Access runner'),
			      'restrict access' => TRUE,
			    ),

		     );
}

////////////////// * RUNNER SECTION OPEN * ///////////////////////////////////////

/**
 * Created the form for runner page
 * runner can search the photos by selecting the event name
 * @param $bucket
 * $bucket give the selected event name
*/

function select_event_runner_get_photos($bucket)
{


	$form['setfield']=array(
	    '#type' => 'fieldset',
	    '#title' => t(''),
	    '#collapsible' => FALSE,
	    '#collapsed' => FALSE,
	    '#attached'=>array('css' => array(drupal_get_path('module', 'runner') . '/runner.css')),
	    
	  );

	//select event in the runner side
	$form['setfield']['events_select_runner']=array('#type'=>'select','#title'=>'Get My Photos','#id'=>'event_runner');

	$form['setfield']['events_select_runner']['#options']=array('select_event'=>"Select Event");
	$event_name=amazon_s3_get_buckets();
	foreach($event_name as $event_name_value)
	{
		$event_title=$event_name_value;
		if($event_title!='home_page')
			$form['setfield']['events_select_runner']['#options'][$event_title]=$event_title;
	}
	if(isset($bucket) && ($bucket!='') && ($bucket=='home_page'))
	{
		$form['setfield']['events_select_runner']['#default_value']=$form['setfield']['events_select_runner']['#options']['select_event'];
	}
	
	else
	{
		$form['setfield']['events_select_runner']['#default_value']=$form['setfield']['events_select_runner']['#options'][$bucket];
	}



	//text field for get the runner number
	$form['setfield']['runner_number']=array('#type'=>'textfield','#title'=>'','#size'=>'20','#id'=>'runner_number','#value'=>'My Number','#attributes'=>array('onclick'=>'return my_number_hide();','onblur'=>'my_number_show();'),'#prefix'=>"<div style='float:left'></div>");

  	//submit get my photo in the runner side
	$form['setfield']['search']=array('#type'=>'submit','#value'=>'search','#prefix'=>"<div style='float:right;margin-left:15px;'></div>",'#attributes'=>array('onclick'=>'return search_validation();'));

	return $form;

}

/** 
 * Function for runner photo search submit.
 */
function select_event_runner_get_photos_submit($form,&$form_state)
{

	$bucket=$form['setfield']['events_select_runner']['#value'];
	$form_state['redirect'] = "runner/".$bucket;

}

/** 
 * Function for buy the images
 * @param $bucket
 *   $bucket is the event name 
 * @return 
 *   return form values
 */
function select_event_runner_sell_photos($bucket)
{
	//for sell the photos in the runner side
	$form['sellfield']=array(
	    '#type' => 'fieldset',
	    '#title' => t(''),
	    '#collapsible' => FALSE,
	    '#collapsed' => FALSE,
	    '#attached'=>array('css' => array(drupal_get_path('module', 'amazon_s3') . '/amazon_s3.css')),
	    
	  );

	$form['sellfield']['events_select_runner']=array('#type'=>'select','#title'=>'Sell My Photos','#attributes'=>array('onchange'=>'return select_event_runner_sell();'),'#id'=>'event_runner_sell');

	$form['sellfield']['events_select_runner']['#options']=array('select_event'=>"Select Event");
	$event_name_sell=amazon_s3_get_buckets();
	foreach($event_name_sell as $event_name_value_sell)
	{
		$event_title_sell=$event_name_value_sell;
		$form['sellfield']['events_select_runner']['#options'][$event_title_sell]=$event_title_sell;
	}

	$form['sellfield']['get_started']=array('#type'=>'submit','#value'=>'Get Started');
	
	return $form;
}


/**
 * Function for search the images by runner
 * @param $bucket
 *   $bucket is event name
 * @return 
 *   return rendered drupal form
 */
function amozon_s3_show_images($bucket)
{
	if($bucket=='')
	{
		$bucket='home_page';
	}
	$s3 = amazon_s3_get_instance();
	$objects = $s3->getBucket($bucket, NULL, NULL, 100);
	foreach ($objects as &$object) {
	$temp_link[]=amazon_s3_get_object_url($bucket, $object['name']);
	}
	$table='<table>';
	for($i=0;$i<count($objects);$i+=5)
	{

		$table.='<tr>';
		if(isset($temp_link[$i]) && ($temp_link[$i]!=''))
	 		$table.="<td><img src='$temp_link[$i]' alt='image' width=100px height=100px  />	</td>";

		if(isset($temp_link[$i+1]) && ($temp_link[$i+1]!=''))
		{
			$j=$i+1;
			$table.="<td><img src='$temp_link[$j]' alt='image' width=100px height=100px  />	</td>";

		}

		if(isset($temp_link[$i+2]) && ($temp_link[$i+2]!=''))
		{
			$k=$i+2;
			$table.="<td><img src='$temp_link[$k]' alt='image' width=100px height=100px  />	</td>";
		}
	
		if(isset($temp_link[$i+3]) && ($temp_link[$i+3]!=''))
		{
			$m=$i+3;
			$table.="<td><img src='$temp_link[$m]' alt='image' width=100px height=100px  /></td>";
		}
	
	
		if(isset($temp_link[$i+4]) && ($temp_link[$i+4]!=''))
		{
			$n=$i+4;
			$table.="<td><img src='$temp_link[$n]' alt='image' width=100px height=100px  />	</td>";
		}
			

		$table.="</tr>";
	
	}
	$table.='</table>';

	$select_event_runner_get_photos = drupal_render(drupal_get_form('select_event_runner_get_photos', $bucket));

	$select_event_runner_sell_photos = drupal_render(drupal_get_form('select_event_runner_sell_photos', $bucket));


	$style="<span style='float:left'><div>$select_event_runner_get_photos</div><div>$select_event_runner_sell_photos </div></span><span style='float:left'>$table</span>";

	return $style;
}


////////////////// * RUNNER SECTION CLOSE * ///////////////////////////////////////
