<?php
/**
 * Init function for adding the external file
 */

function runner_init()
{
	//to add the js file
	drupal_add_js(drupal_get_path("module","runner")."/runner.js");
	drupal_add_css(drupal_get_path('module', 'runner') . '/runner.css');
}

///////////////////////////////////////////////////////////
/** 
 * Create the hook menu for each page 
 * by using this we can map to the related page
 * @return
 * return menu items
 */
function runner_menu()
{
	//url for runner
	$items['runner'] = array(
			    'title' => 'Photo Gallery',
			    'description' => t('View the objects in a event on your Amazon S3 account.'),
			    'page callback' => 'amozon_s3_show_images',
			    'page arguments' => array(1),
			    'access arguments' => array('access_runner'),
			    'type' => MENU_CALLBACK,
			  );
     

	return $items;

}

/**
 * Set the pemission for each url in the admin side
 * so we can the restrict the particular page to accessed by the anonymouse user
*/
function runner_permission()
{

	return array(
			    'access_runner' => array(
			      'title' => t('Access runner'),
			      'description' => t('Access runner'),
			      'restrict access' => TRUE,
			    ),
                          
		     );
}


/**
 * Created the form for runner page
 * runner can search the photos by selecting the event name
 * @param $bucket
 * $bucket give the selected event name
*/

function select_event_runner_get_photos($form,&$form_state)
{

	$form=array();
	$form['setfield']=array(
	    '#type' => 'fieldset',
	    '#title' => t(''),
	    '#collapsible' => FALSE,
	    '#collapsed' => FALSE,
	    '#attached'=>array('css' => array(drupal_get_path('module', 'runner') . '/runner.css')),
	    
	  );

	//select event in the runner side
	$form['setfield']['events_select_runner']=array('#type'=>'select','#title'=>"<div  id='find'>Find</div> <div id='great_photos'>great photos of you...</div>",'#id'=>'event_runner');
	$form['setfield']['events_select_runner']['#options']=array('select_event'=>"Select Event");
	//select event options from content type 'event'
	$runner_search = new runner_search();
	//get the event name from content type 'event'
	$event_name=$runner_search->get_event_name();
	foreach($event_name as $event_name_value)
	{
		$event_title = $event_name_value->title;
		$event_title_nid = $event_name_value->nid;
		$form['setfield']['events_select_runner']['#options'][$event_title_nid]=$event_title;
	}

	//text field for get the runner number
	$form['setfield']['runner_number']=array('#type'=>'textfield','#title'=>'','#size'=>'20','#id'=>'runner_number','#value'=>'My Number','#attributes'=>array('onclick'=>'return my_number_hide();','onblur'=>'my_number_show();'),'#prefix'=>"<div style='float:left'></div>");

  	//submit get my photo in the runner side
	$form['setfield']['search']=array('#type'=>'submit','#value'=>'','#prefix'=>"<div style='float:right;margin-left:15px;'></div>",'#attributes'=>array('onclick'=>'return search_validation();'));

	return $form;

}

/** 
 * Function for runner photo search submit.
 */
function select_event_runner_get_photos_submit($form,&$form_state)
{

	$taxonomy_term_id = $form['setfield']['events_select_runner']['#value'];
	
	$form_state['redirect'] = "runner/".$taxonomy_term_id;

}

/** 
 * Function for buy the images
 * @param $bucket
 *   $bucket is the event name 
 * @return 
 *   return form values
 */
function select_event_runner_sell_photos($form,&$form_state,$bucket)
{
	//for sell the photos in the runner side
	$form['sellfield']=array(
	    '#type' => 'fieldset',
	    '#title' => t(''),
	    '#collapsible' => FALSE,
	    '#collapsed' => FALSE,
	    '#attached'=>array('css' => array(drupal_get_path('module', 'amazon_s3') . '/amazon_s3.css')),
	    
	  );

	$form['sellfield']['events_select_runner']=array('#type'=>'select','#title'=>'<div id="trade">Trade</div>  <div id="taken_picture">pictures you have taken...</div>','#attributes'=>array('onchange'=>'return select_event_runner_sell();'),'#id'=>'event_runner_sell');

	$form['sellfield']['events_select_runner']['#options']=array('select_event'=>"Select Event");
	//select event options from content type 'event'
	$runner_search = new runner_search();
	//get the event name from content type 'event'
	$event_name=$runner_search->get_event_name();
	foreach($event_name as $event_name_value)
	{
		$event_title = $event_name_value->title;
		$event_title_nid = $event_name_value->nid;
		$form['sellfield']['events_select_runner']['#options'][$event_title_nid]=$event_title;
	}

	$form['sellfield']['get_started']=array('#type'=>'submit','#value'=>'');
	
	return $form;
}


/**
 * Function for search the images by runner
 * @param $bucket
 *   $bucket is event name
 * @return 
 *   return rendered drupal form
 */
function amozon_s3_show_images($bucket)
{
       

	$select_event_runner_get_photos = drupal_render(drupal_get_form('select_event_runner_get_photos', $bucket));

	$select_event_runner_sell_photos = drupal_render(drupal_get_form('select_event_runner_sell_photos', $bucket));


	$style="<span style='float:right'><div>$select_event_runner_get_photos</div><div>$select_event_runner_sell_photos </div></span>";

	return $style;
}


