<?php

/**
 * product Node view function
 */
/*function ubercart_custom_node_view($node, $view_mode, $langcode) {
 global $user;
 $uid = $user->uid;
 $node_type = $node->type;
 if (($uid != 1) && (arg(0) == 'node') && ($node_type == 'product')) {
 drupal_goto();
 }
 if ($node->type == 'product' && $view_mode == 'full') {

 $xyobject = new ubercart_custom_model();
 $xyvalues = $xyobject->getxyvalues($node->nid);

 $header = array(
 array('data' => t('Sl.no')), array('data' => t('Runner Number')), array('data' => t('X-Value')), array('data' => t('Y-Value')),array('data' => t('Probability'))
 );
 $rows = array();
 $xycount = 0;
 foreach($xyvalues as $xyvalue){

 $xycount++;
 $rows[] = array(
 array('data' => $xycount),
 array('data' => $xyvalue->number),
 array('data' => $xyvalue->position_left),
 array('data' => $xyvalue->position_top),
 array('data' => $xyvalue->probability)
 );

 }


 if($xycount>0){
 $node->content['body'][0]['#markup'] =  theme('table', array('header' => $header, 'rows'=> $rows));
 }



 }
 }
 */

/**
 * Implements hook_views_api().
 */
function ubercart_custom_views_api() {
  return array(
        'version' => '3.0', 
        'path' => drupal_get_path('module', 'ubercart_custom') . '/views');
}

/**
 * Alter the menu items
 */
function ubercart_custom_menu_alter(&$items) {
  unset($items['cart']);
}


/**
 * Init function for adding the external file
 */
function ubercart_custom_init() {
  require_once(DRUPAL_ROOT . '/' . drupal_get_path('module', 'ocr') . '/ocr_product_node_saver.inc');

  drupal_add_css( 'http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.13/themes/start/jquery-ui.css', 'external');
  drupal_add_js('https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.13/jquery-ui.min.js', 'external');

  drupal_add_css(drupal_get_path('module', 'ubercart_custom') . '/ubercart_custom.css');
  drupal_add_js(drupal_get_path('module', 'ubercart_custom') . '/ubercart_custom.js');

  //for redirect the cart page
  //when no products in the shopping cart
  if (arg(0) == 'cart' && arg(1) == '') {
    $no_of_cart_items = count(uc_cart_get_contents());
    if ($no_of_cart_items == '0') {
      drupal_set_message(t('There are no products in your shopping cart'));
      drupal_goto();
    }
  }
  variable_set('max_order_value', 12);
}


function get_max_order_value() {
  $currency = current_currency_code();
  $max_price = package_price($currency);
  return $max_price;
}

function package_price($currency) {
  $defaults = array(
    'GBP' => 12,
    'RUB' => 500,
    'EUR' => 15,
    'USD' => 20,
  );
  
  return isset($defaults[$currency]) ? $defaults[$currency] : variable_get('max_order_value', 12);
}

function get_cart_total_with_discount($total) {
  $max_order_value = get_max_order_value();
  if ($total > $max_order_value) {
    return $max_order_value;
  } 
  else {
    return $total;
  }
  
}

/**
 * Create the hook menu for each page
 * by using this we can map to the related page
 * @return
 * return menu items
 */
function ubercart_custom_menu() {
  //AJAX urls
  $items['ajax/cart_remove_item'] = array(
    'title' => '',
    'description' => '',
    'page callback' => 'cart_remove_item',
    'access arguments' => array('search photos'),
    'type' => MENU_CALLBACK
  );
  $items['ajax/cart_add_item'] = array(
    'title' => 'api point that adds item to the cart.',
    'description' => '',
    'page callback' => 'cart_add_item',
    'access arguments' => array('search photos'),
    'type' => MENU_CALLBACK
  );
  $items['ajax/cart_list_items'] = array(
    'title' => '',
    'description' => 'api point that returns json with list of items in the cart',
    'page callback' => 'cart_list_items',
    'access arguments' => array('search photos'),
    'type' => MENU_CALLBACK
  );
  $items['ajax/cart_clear'] = array(
    'title' => '',
    'description' => 'api point that clears cart of current user',
    'page callback' => 'cart_clear',
    'access arguments' => array('search photos'),
    'type' => MENU_CALLBACK
  );
  $items['ajax/save_numbers'] = array(
    'title' => '',
    'description' => 'api point that saves numbers on product',
    'page callback' => 'save_numbers',
    'access arguments' => array('edit own product content'),
    'type' => MENU_CALLBACK
  );
  $items['ajax/change_price'] = array(
    'title' => '',
    'description' => 'api point that saves new price on product',
    'page callback' => 'change_price',
    'access arguments' => array('edit own product content'),
    'type' => MENU_CALLBACK
  );

  $items['admin/store/settings/checkout/edit/fields_lang'] = array(
    'title' => 'Translate address fields',
    'description' => 'Translate the address field names',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ubercart_custom_uc_store_address_fields'),  
    'access arguments' => array('administer store'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 8,
  );


  return $items;
}

/**
 *
 * Function that adds product to cart for the AJAX calls on /cart_add_item?nid={nid}
 */
function cart_add_item() {
  if (!isset($_POST['nid'])) {
    echo json_message(FALSE, array('message' => t('Required parameter nid is not set.')));
    return;
  }
  $nid = $_POST['nid'];
  $cid = uc_cart_get_id($create = TRUE);

  // check whether item is already in the cart
  foreach (uc_cart_get_contents($cid) as $item) {
    if ($nid == $item->nid) {
      echo json_message(FALSE, array('message' => t('Did not add item. Item @nid is already in the cart.', array('@nid' => $nid ))));
      return;
    }
  }
  // add item to cart
  $url = uc_cart_add_item($nid, $qty = 1, $data = NULL, $cid);
  
  $count = count_cart_items($cid);
  $total = get_cart_total_with_discount(cart_total_amount($cid));
  
  // check whether product currency is different from 
  
  echo json_message(TRUE, array(
    'message' => 'Added item to cart: ' . $url . '. Node Id: ' . $nid . '. cid:' . $cid,
    'count' => $count,
    'total' => $total));
   
}

/**
 * Implements hook_uc_order
 * See: http://www.ubercart.org/docs/api/hook_order
 */
function ubercart_custom_uc_order($op, &$order, $arg2) {
  $max_order_value = get_max_order_value();
  
  switch ($op) {
    case 'load':
      break;
    case 'save':
    
      // The first thing we do is remove the line item if it exists. Since users can go back and forth from the order review page to the checkout page, they may make different selections each time. By defaulting to having the line item removed, we prevent accidentally adding it multiple times, as well as preventing adding it if the user hasn't selected it when reviewing the page. So we loop through the existing line items searching for our specific line item, and removing it if it exists. We will add it afterwards if it needs to be added.
      foreach ($order->line_items as $key => $line_item) {
        if ($line_item['type'] == 'gift_discount') { // 'gift_wrap' is the line item ID that will be defined after this loop.
          unset($order->line_items[$key]);
          db_query('DELETE FROM {uc_order_line_items} WHERE order_id = :oid AND type = :type',  array(':oid' => $order->order_id, ':type' => 'gift_discount'));
          break;
        }
      }

      // Now we can get the total value of the order
      $subtotal = order_line_amount($order, 'subtotal');
     
      $discount = 0;
      if ($subtotal > $max_order_value) {
        $discount = $subtotal - $max_order_value;
      }
      else {
        break;
      }

      // We will enter this conditional when the checkbox was selected.
      // In this tutorial, the amount of the line item is a fixed amount, 3 pounds, but in my real tutorial the value was a percentage of the total, as I explained above in the hook_line_order() explanation. You will most likely need to re-calculate the value of the line item again here, however in this tutorial it is a fixed amount.
      $line_item_value = $discount;
      // Next we add the line item
      uc_order_line_item_add
      (
        $order->order_id, // This is the order ID.
        'gift_discount', // This is the line item ID. We used this ID to remove the line item in the loop above.
        t('Package Discount'), // This is the text that will be shown on the order review page to describe what the line item is
        -1 * $discount, // This is the value of the line item. Discounts will be a negative number, surcharges a positive number
        NULL, // This is the weight of the line item
        array() // Here you can pass any data that your module will use for itself when the order is submitted. In the case of my real module, I passed the value of the message that should be attached to the order when the user purchases gift wrapping. In this module there is no custom value so I actually wouldn't even pass the empty array normally. I just put it here to explain how it can be used.
      );

      break;
    case 'total':
      // Here we return a value that will be added to the order total. For discounts we would return a negative value, for surcharges we return a positive value. We do NOT return the new total, only the change in the total.
      // We loop through each of the line items to see if ours has been added. If it has, we adjust the order total accordingly.
      foreach ($order->line_items as $line_item) {
        if ($line_item['type'] == 'gift_discount') { // 'gift_discount' is the ID of the line item as defined when $op equals 'save'
          // If we enter this, the line item exists, so we need to return the value of the line item. This will adjust the order total.
          return $line_item['amount'];
        }
      }
      break;

    case 'delete':
      // Delete existing order codes

      //TO DO: determine if uses should be deleted or put global setting in for user to decide
      break;
    case 'update':
      if ($arg2 == 'abandoned') {
        rules_invoke_event('ubercart_custom_order_abandoned', $order);
      }
      break;
  }
}

/**
 *  implments hook_uc_checkout_complete
 */
function ubercart_custom_uc_checkout_complete($order, $account) {

  $discount = order_line_amount($order, 'gift_discount');
  if ($discount == 0) {
    return;
  }
  
  $subtotal = order_line_amount($order, 'subtotal');
 
  $item_discount = 0.0000;
  // ubercart just saved completed order
  foreach ($order->products as $order_product_id => $product) {
    // calculate discount proportionally to price of a product
    $item_discount = -($product->price / $subtotal) * $discount;
    log_order_product_discount($order_product_id, $item_discount);
  }

}

/**
 * 
 * Gets amount for the specified line type in the order.
 * @param object $order
 * @param string $line_type
 */
function order_line_amount($order, $line_type) {
  $amount = 0;
  foreach ($order->line_items as $item) {
    // need to get price from the node in case it was set to 0 already...
    if ($item['type'] == $line_type) {
      $amount += $item['amount'];
    }
  }
  return $amount;
}


/**
 *
 * Function that removes product from cart for the AJAX calls on /cart_add_item?nid={nid}
 */
function cart_remove_item() {
  
  if (!isset($_POST['nid'])) {
    echo json_message(FALSE, array('message' => t('Required parameter nid is not set.')));
    return;
  }

  $nid = $_POST['nid'];
  $cart_ids = array();
  $cid = uc_cart_get_id($create = TRUE);
  $item_removed = FALSE;
  $removed_item = NULL;
  foreach (uc_cart_get_contents($cid) as $item) {
    if ($nid == $item->nid) {
      uc_cart_remove_item($nid, $cid, $data = array('module' => 'uc_product')); //, $cid = $uid, $data = array('module' => 'uc_product'));
      $item_removed = TRUE;
      $removed_item = $item;
      break;   
    }
  }
  if ($item_removed) {
    $count = count_cart_items($cid) - 1;
    $total = get_cart_total_with_discount(cart_total_amount($cid) - $removed_item->price * $removed_item->qty);
    
    echo json_message(TRUE,
        array(
          'message' => t('Removed item from the cart.'),
          'nid' => $nid,
          'count' => $count,
          'total' => $total,
        )
      );
      return;
  } 
  else {
    echo json_message(FALSE, array('message' => t('Item was not found in the cart.'), 'nid' => $nid));
  }
}

function order_summary_text() {

}

/**
 *
 * Counts number of items in the cart for given cart id
 * @param integer $cid
 */
function count_cart_items($cid) {
  return count(uc_cart_get_contents($cid));
}

/**
 * Gets subtotal of the cart for given cart id
 *
 * @param integer $cid - cart id
 */
function cart_total_amount($cid) {
  $subtotal = 0;
  $code = current_currency_code();
  
  foreach (uc_cart_get_contents($cid) as $item) {
    
    $price = 0;
    $item_currency = isset($item->field_currency[LANGUAGE_NONE])? $item->field_currency[LANGUAGE_NONE][0]['value'] : 'GBP';
    if ($item_currency != $code) {
       $result = currency_api_convert($item_currency, $code, $item->price);
       $price = $result['value'];
    }
    else {
      $price = $item->price;
    }
   watchdog('ajax', 'price = ' . $price);
    $subtotal += $price * $item->qty;
  }
  
  if ($subtotal > 100) {
    return number_format($subtotal,0);   
  }
  else {
    return number_format($subtotal, 2);   
  }
 
}


/**
 *
 * Counts number of photographers who took photos that were selected in the cart.
 * @param integer $cid
 */
function count_cart_photographers($cid) {
  $cart = uc_cart_get_contents($cid);

  foreach ($cart as $index => $product) {
    $photographer[] = $product->uid;
  }

  return count(array_unique($photographer));

}

/**
 *
 * Function that generates JSON message that can be returned for AJAX call
 * @param boolean $success shows whether request was actioned successfully
 * @param string $message message that will be added to the response.
 * 	Message attribute will be ignored if not provided or NULL.
 */
function json_message($success, $attributes = array()) {
  $result = array('success' => $success);

  foreach ($attributes as $index => $attribute) {
    $result[$index] = $attribute;
  }
  return json_encode($result);
}

/**
 * AJAX call
 * returns json with the list of items in the cart of current user
 */
function cart_list_items() {
  $event = $_POST['event'];
  $number = $_POST['number'];
  
  $cid = uc_cart_get_id($create = TRUE);
  
  // remove cart items selected in previous searches
  uc_cart_remove_items_new_search($cid, $event, $number);
   
  $items = array();
  foreach (uc_cart_get_contents($cid) as $item) {
    $items[]=array('nid' => $item->nid, 'price' => $item->price, 'qty' => $item->qty);
  }
  
  $count = count_cart_items($cid);
  $total = get_cart_total_with_discount(cart_total_amount($cid));
  
  $result = array(
    'total' => $total,
    'items' => $items,
    'event' => $event,
    'number' => $number,
    'count' => $count,
  );
  echo json_encode($result);
  
  
}

/**
 * 
 * Remove items from cart that don't match the search
 * @param integer $event_id
 * @param integer $number
 */
function uc_cart_remove_items_new_search($cid, $event, $number) {
  
  $items = uc_cart_get_contents($cid);
  
  foreach ($items as $item) {
    $nid = $item->nid;
    $node = node_load($nid);
    $item_numbers = field_get_items('node', $node, 'field_ocr_numbers', $node->language);
    $item_event = field_get_items('node', $node, 'field_event_reference', $node->language);
   
    if ($item_event[0]['nid'] == $event) {
/*     Find a better way to restrict cart items
       $same_number = FALSE;
       foreach ($item_numbers as $item_number) {
         if (partial_match($item_number['value'], $number)) {
           $same_number = TRUE;
         }
       }
       if (!$same_number) {
         watchdog('debug', 'Removing item from cart due to different number: ' . $nid);
          uc_cart_remove_item($nid, $cid, $data = array('module' => 'uc_product'));   
       } */
    } 
    else { // event in the search is different
      uc_cart_remove_item($nid, $cid, $data = array('module' => 'uc_product'));
    } 
  }
}
/**
 * 
 * Checks whether one of the values contains the other value
 * @param unknown_type $val1
 * @param unknown_type $val2
 */
function partial_match($val1, $val2) {
  // convert values to string
  $strval1 = strval($val1);
  $strval2 = strval($val2);
  // check if there is a partial match
  if (strpos($strval1, $strval2) !== FALSE || strpos($strval2, $strval1) !== FALSE) {
    return TRUE;
  } 
  else {
    return FALSE;
  }
}

/**
 * AJAX call
 * Clears the cart of the current user
 */
function cart_clear() {
  uc_cart_empty(uc_cart_get_id());
  echo json_message(TRUE, array(
    'message' => 'Cart was cleared.',
    'count' => 0,
    'total' => 0,
    )
  );
}

/**
 * Form alter function
 * by using this form_alter function we can alter the form without editing core module
 * @param $form,$form_state,$form_id
 * $form give the form value
 * $form_id is the form id
 */
function ubercart_custom_form_alter(&$form, $form_state, $form_id) {

  //alter the product node edit form
  if ($form['#form_id'] == 'product_node_form') {
    $nid = $form['nid']['#value'];
    $node_order_status = new ubercart_custom_model();
    $status_of_image = $node_order_status->image_order_status($nid);
    //Check the product already sold or not
    //if sold means disable the selling price in the product edit forms
    if ($status_of_image != 0) {
      $form['base']['prices']['sell_price']['#disabled'] = 'TRUE';
    }
  }

  //alter the checkout form
  if ($form['#form_id'] == 'uc_cart_checkout_form') {

    //$form['panes']['payment']['payment_method']['#options']['paypal_wps'] = 'Paypal Standard';
    //$form['panes']['payment']['details']['#markup'] = '';


   // $form['panes']['billing']['#type'] = '';
   // $form['panes']['customer']['#type'] = '';
   // $form['panes']['cart']['#type'] = '';

  //  $form['panes']['customer']['email_text']['#prefix'] =  '<span class="checkout-email">';
  //  $form['panes']['customer']['email_text']['#suffix'] =  '</span>';


   // $form['panes']['payment']['payment_method']['#type'] = 'hidden';
   // $form['panes']['payment']['details']['cc_number']['#required'] = TRUE;
  //  $form['panes']['payment']['details']['cc_cvv']['#required'] = TRUE;


  //  $form['panes']['payment']['details']['cc_policy']['#markup'] = '';
  //  $form['panes']['payment']['details']['cc_number']['#size'] = '32';
  //  $form['panes']['payment']['details']['cc_exp_month']['#title'] = 'Expiration Month';
    $form['actions']['cancel'] = '';
  //  $form['actions']['continue']['#value'] = '';

  } 

  //alter for review order page
  if ($form['#form_id'] == 'uc_cart_checkout_review_form') {
    $form['actions']['back']= '';
 /*   $form['actions']['back']['#markup'] = l("", "cart/checkout", array(
                                          'attributes' => array(
                                            'id' => 'edit-back',

    )));
 */
    $form['actions']['submit']['#value'] = t('');

  }
}


/**
 * AJAX call
 * Function that adds/removes runners' numbers from product node
 * @return
 * JSON message that can be returned for AJAX call
 */
function save_numbers() {
  $nid = $_POST['nid'];
  $number = $_POST['number'];
  $option = $_POST['option'];
  
  global $user;
  $uid = $user->uid;

  if (empty($nid) || empty($number) || empty($option)) {
    echo json_message(FALSE, array('message' => t('Required parameter is not set')));
    return;
  }

  $number_int = (int) $number;

  if ((string)$number_int != $number) {
    echo json_message(FALSE, array('message' => t('Number is not int')));
    return;
  }

  //check permission
  $node = node_load($nid);
  if (!node_access("update", $node)) {
    echo json_message(FALSE, array('message' => t('Has no permissions')));
    return;
  }

  $productSaver = new ProductNodeSaver($nid);

  switch ($option) {
    case "add":
      $arr_number = array('value' => $number, 'manual' => 1, 'probability' => 1);
      $productSaver->AddNumber($arr_number);
      $productSaver->SetVerifiedBy($uid);
      break;

    case "remove":
      $productSaver->RemoveNumber($number);
      $productSaver->SetVerifiedBy($uid);
      break;

    default:
      echo json_message(FALSE, array('message' => t('Parametr option=@option is not supported', array('@option' => $option))));
      return;
  }

  $productSaver->Save();

  echo json_message(TRUE, array('message' => 'node=' . $nid . ',number=' . $number . ',option=' . $option));
  return;
}

/**
 * AJAX call
 * Function that changes price from product node
 * @return
 * JSON message that can be returned for AJAX call
 */
function change_price() {
  $nid = $_POST['nid'];
  $price  = $_POST['price'];
  if (empty($nid) || empty($price)) {
    echo json_message(FALSE, array('message' => t('Required parametr is not set')));
    return;
  }

  //check permission
  $node = node_load($nid);
  if (!node_access("update", $node)) {
    echo json_message(FALSE, array('message' => t('Has no permissions')));
    return;
  }

  $productSaver = new ProductNodeSaver($nid);
  $productSaver->SetPrice($price);
  $productSaver->Save();

  echo json_message(TRUE, array('message' => t('New price was set to @price', array('@price' => $price)), 'nid' => $nid, 'price' =>  $price));
  return;
}

/*
 * Enable traslation of the uberacart Adress fields.
 */
function ubercart_custom_uc_store_address_fields() {
  $form = array();
  //Copied from uc_store_address_fields_form
  $fields = array(
    'first_name' => array(t('First name'), TRUE),
    'last_name' => array(t('Last name'), TRUE),
    'phone' => array(t('Phone number'), TRUE),
    'company' => array(t('Company'), TRUE),
    'street1' => array(t('Street address 1'), TRUE),
    'street2' => array(t('Street address 2'), TRUE),
    'city' => array(t('City'), TRUE),
    'zone' => array(t('State/Province'), TRUE),
    'country' => array(t('Country'), TRUE),
    'postal_code' => array(t('Postal code'), TRUE),
    'address' => array(t('Address'), FALSE),
    'street' => array(t('Street address'), FALSE),
  );
  //Just loop and build the fields
  foreach ($fields as $field => $data) {
    $form['uc_field_' . $field] = array(
        '#type' => 'textfield',
        '#title' => $data[0],
        '#default_value' => $data[0],//variable_get('uc_field_'.$field, $data),    
    );
  }
  //Magic happens
  return system_settings_form($form);
}

/**
 * Upserts order product discount
 */ 
function log_order_product_discount($order_product_id, $discount) {
  $result = db_merge('uc_custom_order_discounts')
      ->key(array('order_product_id' => $order_product_id, ))
      ->fields(array('amount' => $discount, ))
      ->execute();
}