<?php

function runmemo_init()
{
	//to add the js file
	drupal_add_js(drupal_get_path("module","runmemo")."/runmemo.js");

}



//form alter function
function runmemo_form_alter(&$form, $form_state, $form_id)
{




	if($form['#form_id']=='amazon_s3_file_upload_form')
	{

		

		//for changing the single file upload to drag and drop file upload change #type=>plupload
		$form['box']['file']['#type']='plupload';
		
		//change the already existing button value upload->start upload
		$form['box']['upload']['#value']='Upload';


		


	}

	//registration page
	if($form['#form_id']=='user_register_form')
	{
	
	

		$base_path=base_path().'sites/default/help_icon.gif';

		//create the select role radio buttons in the create account page
		/*
		$form['field_select_user']=array('#type' => 'radios','#title'=> 'Select Role','#id'=> 'role','#attributes'=>array('onclick'=>'user_photographer()'),'#options'=>array('runner'=>'Runner','photographer'=>'Photographer'),'#weight'=>'4','#required'=>'1');
		*/		
	
		//$form['field_select_user2']=array('#markup'=>"<div id='paypal_title' style='color:black'>Paypal Account Id</div>",'#weight'=>'5');

                $form['photo_paypal_id']=array('#type'=>'textfield','#title'=> 'Paypal Account Id','#id'=> 'paypal_account_id','#weight'=>'6','#required'=>'1');

		$form['photo_paypal_icon']=array('#markup'=>"<p><span title='Your Paypal account ID' id='paypal_icon' style='float:right;padding-right:102px;padding-top:18px;color:red;'><img src='$base_path'></img></span></p>",'#weight'=>'5');


		//add the form submit function for insert the user role in the user table
                $form['#submit']['1']= 'user_role_insertion'; 
		//$form['#validate']['4'] = 'my_mod_my_form_id_validate';


	}

	//profile edit page
	
	if($form['#form_id']=='user_profile_form')
	{

		global $user;
		$uid=$user->uid;
		

		$base_path=base_path().'sites/default/help_icon.gif';

		$form['photo_paypal_id']=array('#type'=>'textfield','#title'=> 'Paypal Account Id','#id'=> 'paypal_account_id','#weight'=>'6','#required'=>'1');

		$form['photo_paypal_icon']=array('#markup'=>"<p><span title='Your Paypal account ID' id='paypal_icon' style='float:right;padding-right:102px;padding-top:18px;color:red;'><img src='$base_path'></img></span></p>",'#weight'=>'5');

		$paypal_id=db_query("SELECT paypal_account_id FROM photographer_account WHERE uid=$uid");
		foreach($paypal_id as $paypal_id_value)
		{
			$paypal_ac_id=$paypal_id_value->paypal_account_id;
			$form['photo_paypal_id']['#value']=$paypal_ac_id;
		}

		
		$form['#submit'][1]='edit_user_profile_submit';

	}
}


//function for insert the user role in the user table when submit the create account submit button
function user_role_insertion($form,&$from_state)
{

	$user_role=db_query("SELECT rid FROM role WHERE name='Photographer'");
	foreach($user_role as $user_role_value)
	{
		$role_id=$user_role_value->rid;
	}
	$uid=$form['#user']->uid;
	db_query("Update users SET role=$role_id WHERE uid=$uid");
	
	//insert the paypal account id in the photographer account table
	if(isset($form['#user']->photo_paypal_id) && ($form['#user']->photo_paypal_id != ''))
	{
		$photographer_account_id=$form['#user']->photo_paypal_id;
		
		db_insert('photographer_account')
				      	->fields(array(
					'paypal_account_id' => $photographer_account_id,
					'uid' => $uid,
					))->execute();

		db_insert('users_roles')
				      	->fields(array(
					'uid' => $uid,
					'rid' => $role_id,
					))->execute();
		//drupal_goto('<front>');
	}
}

//submit function edit user profile page
function edit_user_profile_submit($form,&$from_state)
{
	
	
	$uid=$form['#user']->uid;
	$paypal_id=$_POST['photo_paypal_id'];

	$paypal_uid=db_query("SELECT uid FROM photographer_account ");
	foreach($paypal_uid as $paypal_uid_value)
	{
		$paypal_uid_id[]=$paypal_uid_value->uid;
		
	}

	if(in_array($uid,$paypal_uid_id))
	{
		db_query("UPDATE photographer_account SET paypal_account_id=$paypal_id WHERE uid=$uid");

	}

	if(!in_array($uid,$paypal_uid_id))
	{

		db_insert('photographer_account')
				      	->fields(array(
					'paypal_account_id' => $paypal_id,
					'uid' => $uid,
					))->execute();

	}
	
}


