<?php

module_load_include('inc', 'photo_tagger', 'photo_tagger');

function photo_tagger_init() {
  if ('tag' === arg(1)) {
    drupal_add_js(drupal_get_path('module', 'photo_tagger') . '/photo_tagger.js');
    drupal_add_css(drupal_get_path('module', 'photo_tagger') . '/photo_tagger.css');
    drupal_add_js(drupal_get_path('module', 'bib_number') . '/jquery.tagsinput.js');
    drupal_add_css(drupal_get_path('module', 'bib_number') . '/jquery.tagsinput.css');
  }
}


/**
 * Implements hook_menu
 */
function photo_tagger_menu() {

   $items['photographer/tag'] = array(
      'title' => 'Tag Photos',
      'menu_name' => 'navigation',
      'description' => 'View the objects in a bucket on your Amazon S3 account.',
      'page callback' => 'photographer_tag_page',
      'access arguments' => array('access_photographer'),
      'weight' => '1',
      'type' => MENU_NORMAL_ITEM,
  );

  $items['ajax/tagger_get_list'] = array(
    'title' => 'api point that gets products for tagging.',
    'description' => '',
    'page callback' => 'photo_tagger_get_list',
    'access arguments' => array('access_photographer'),
    'type' => MENU_CALLBACK
  );
  
  return $items;

}

function photo_tagger_get_list() {
    // get the node id to start from.
    $nid = $_POST['nid'];
    // get number of items to return.
    $items = 10;
    // field query to select product images.
    global $user;
    $images = photo_tagger_get_photos($nid, $user->uid, $items);
    

    $image_pool = array('image_pool' => $images, 'current'=> 0, 'size' => $items, );
  
  // transform results to json  
  echo json_message(TRUE, array(
    'message' => 'images for tagging.',
    'data' => $image_pool,
   ));

}

function photographer_tag_page() {
  global $user;
  $images = photo_tagger_get_photos(0, $user->uid, 10);
  $image_pool = array('image_pool' => $images, 'current'=> 0, 'size' => 10, );
  $js_data = array('PhotoTagger' => $image_pool);
  drupal_add_js($js_data,'setting');

  return '<form>
            <input type="radio" name="sex" value="tagged">With numbers<br>
            <input type="radio" name="sex" value="untagged">Without numbers
          </form>
    
          <div class="main">
            <div id="image-pool" class="image-pool">
           <img id="image-0" src="' . $images[0]['url']. '" class="active" />
            </div>
            <form>
            <input id="tagsinput" class="tagsinput" />
           </form>
          </div>';
 
}

